---
title: "R Notebook"
output: html_document
---

```{r setup}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")
library(tidyverse)


```

```{r}
tet2_cd14_de = read_tsv("tables/metacells_de_cell_types/CD14 Monos_TET2_vs_none.tsv")
geneformer_isp = readxl::read_excel("input_data/hpb2022_tet2_control_monos_perturb_output_stats.xlsx")
```

```{r}
geneformer_sig = geneformer_isp %>%
  filter(Sig == 1 & Shift_to_goal_end > 0) %>%
  pull(Gene_name)

de_sig = tet2_cd14_de %>%
  filter(padj < 0.05 & log2FoldChange > 0) %>%
  pull(gene)
```

```{r}
(overlap_genes = intersect(geneformer_sig, de_sig)) # overlap = 116 genes out of 1389 DE and 1109 geneformer
```

```{r}
library(clusterProfiler)
library(org.Hs.eg.db)


go_enrich = enrichGO(gene = overlap_genes,
                      universe = intersect(tet2_cd14_de$gene, geneformer_isp$Gene_name),
                      OrgDb = "org.Hs.eg.db", 
                      keyType = "SYMBOL",
                      readable = TRUE,
                      ont = "ALL")

dotplot(go_enrich)
```


```{r}
neg_geneformer_sig = geneformer_isp %>%
  filter(Sig == 1 & Shift_to_goal_end < 0) %>%
  pull(Gene_name)

neg_de_sig = tet2_cd14_de %>%
  filter(padj < 0.05 & log2FoldChange < 0) %>%
  pull(gene)
```

```{r}
(neg_overlap_genes = intersect(neg_geneformer_sig, neg_de_sig)) # overlap = 116 genes out of 1389 DE and 1109 geneformer
```

```{r}


neg_go_enrich = enrichGO(gene = neg_overlap_genes,
                      universe = intersect(tet2_cd14_de$gene, geneformer_isp$Gene_name),
                      OrgDb = "org.Hs.eg.db", 
                      keyType = "SYMBOL",
                      readable = TRUE,
                      ont = "ALL")

dotplot(neg_go_enrich)
```